[CI] ament_lint_cmake skip kortex_drivers
ament_lint_cmake fails due to to known readability/wonkycase
1. FetchContent_Declare
2. FetchContent_MakeAvailable

These mix CamelCase_And_Underscores

Error: kortex_driver/CMakeLists.txt:3: Do not use mixed case commands [readability/wonkycase]
Error: kortex_driver/CMakeLists.txt:8: Do not use mixed case commands [readability/wonkycase]

I couldn't find a way to disable this via an argument.
This test is also skipped via ".pre-commit-config.yaml" on this directory

Signed-off-by: Alex Moriarty <alex.moriarty@picknik.ai>